// main/sprite.h —— table-driven sprite registry. Opaque full-screen backgrounds
// use LVGL I4 palettes; scaled/cropped entities stay BGRA ARGB8888 to avoid the
// indexed decoder's partial-transform path. Animation packs decode one frame.
#pragma once

#include "lvgl.h"
#include <stdint.h>

typedef enum {
    SPR_IDLE0 = 0, SPR_IDLE1,
    SPR_HAPPY0, SPR_HAPPY1, SPR_HAPPY2,
    SPR_AG_WORKING, SPR_AG_NEEDS0, SPR_AG_NEEDS1,
    SPR_AG_REVIEW, SPR_AG_FAILED, SPR_AG_CELEBRATE,
    SPR_HERO_JOB_WHITE, SPR_HERO_JOB_BLACK,
    SPR_OC_POMO_FOCUS, SPR_OC_POMO_REWARD, SPR_OC_CLICKER, SPR_OC_STANDBY_SLEEP,
    SPR_SIDE_KNIGHT, SPR_SIDE_BLACK, SPR_SIDE_WHITE, SPR_SIDE_THIEF, SPR_SIDE_DARK,
    SPR_FRONT_KNIGHT, SPR_FRONT_THIEF, SPR_FRONT_DARK,
    SPR_MON_SLIME, SPR_MON_SLIME_HURT,
    SPR_MON_BAT0, SPR_MON_BAT1, SPR_MON_BAT_HURT,
    SPR_MON_SKEL, SPR_MON_SKEL_HURT,
    SPR_MON_GOLEM, SPR_MON_GOLEM_HURT,
    SPR_MON_MIMIC_CLOSED, SPR_MON_MIMIC_OPEN, SPR_MON_ANCIENT, SPR_MON_ANCIENT_HURT,
    SPR_EVENT_CURSED_GATE, SPR_EVENT_WISHING_WELL,
    SPR_EVENT_RARE_SPARKLE, SPR_EVENT_STARFALL,
    SPR_ULT_CASTLE, SPR_ULT_METEOR, SPR_ULT_SANCTUARY,
    SPR_ULT_JACKPOT, SPR_ULT_ECLIPSE,
    SPR_UI_REBIRTH,
    SPR_UI_ULT_CASTLE, SPR_UI_ULT_METEOR, SPR_UI_ULT_SANCTUARY,
    SPR_UI_ULT_JACKPOT, SPR_UI_ULT_ECLIPSE,
    SPR_UI_AFFIX_LEECH, SPR_UI_AFFIX_GUARD, SPR_UI_AFFIX_SWIFT,
    SPR_UI_AFFIX_VENOM, SPR_UI_AFFIX_SLAYER, SPR_UI_AFFIX_GREED,
    SPR_UI_RESOURCE_ESSENCE, SPR_UI_ITEM_FEATHER,
    SPR_UI_RARITY0, SPR_UI_RARITY1, SPR_UI_RARITY2, SPR_UI_RARITY3, SPR_UI_RARITY4,
    SPR_BG_ROOM, SPR_BG_TOWN, SPR_BG_CAVE, SPR_BG_FIRE, SPR_BG_FROST, SPR_BG_VAULT,
    SPR_COUNT,
} sprite_id_t;

const lv_img_dsc_t *sprite_get(sprite_id_t id);
sprite_id_t sprite_for_mood(int mood, uint32_t tick_500ms);
