# Writes ${OUT} with the host's current Unix epoch (seconds; absolute time,
# timezone-independent). Runs on every build — the consuming target has no
# output file, so ninja/make treat it as always stale.
# Consumer: main/deskpet_time.c seeds the wall clock from it at boot (device
# has no RTC battery and no NTP, so build time is the best known wall time).
string(TIMESTAMP EPOCH "%s")
if(NOT EPOCH MATCHES "^[0-9]+$")
    set(EPOCH "0")
endif()
file(WRITE "${OUT}"
"// generated by tools/gen_build_time.cmake - do not edit or commit\n\
#define DESKPET_BUILD_EPOCH_SEC ${EPOCH}ULL\n")
